name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Sync with Glitch
        uses: wei/git-sync@v1
        env:
          SOURCE_REPO: "https://github.com/mamaiank/boilerplate-project-issuetracker.git"
          SOURCE_BRANCH: "main"
          DESTINATION_REPO: ${{ secrets.glitch_git_URL }}
          DESTINATION_BRANCH: "master"
        with:
          args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH --force
      
      