name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB: ${{ secrets.DB }}
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
      - name: Set Git config
        run: |
          git config receive.denyCurrentBranch ignore
          git remote add ${{ secrets.glitch_git_URL }}
          git fetch ${{ secrets.glitch_git_URL }} master
          git pull ${{ secrets.glitch_git_URL }} master --ff-only
      - name: Push changes to Glitch
        run: |
          git push ${{ secrets.glitch_git_URL }} HEAD:master